trigger:
  branches:
    include:
      - main

pool:
  name: 'MyLocalAgent'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm ci
    displayName: 'Clean Install Dependencies'

  - script: |
      npx playwright install --with-deps
    displayName: 'Install Playwright Browsers & System Deps'

  - script: |
      npx playwright test
    displayName: 'Run Playwright Tests'
    env:
      CI: 'true' # Tells Playwright it's running in a CI environment

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Playwright HTML Report'
    condition: succeededOrFailed()
    inputs:
      targetPath: '$(Build.SourcesDirectory)/playwright-report'
      artifact: 'Playwright-Results'
      publishLocation: 'pipeline'