trigger:
  branches:
    include:
      - main

pool:
  name: MyLocalAgent

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: node -v
  displayName: 'Check Node Version'

- script: npm ci
  displayName: 'Install Dependencies'

- script: npx playwright install
  displayName: 'Install Playwright Browsers'

- script: npx playwright test --reporter=html
  displayName: 'Run Playwright Tests'
  env:
    CI: 'true'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Playwright Report'
  condition: always()
  inputs:
    targetPath: '$(Build.SourcesDirectory)/playwright-report'
    artifact: 'Playwright-Results'
    publishLocation: 'pipeline'